export const NAVIGATION = {
  home: 'Home',
  phone: 'Phone',
  loginPassword: 'LoginPassword',
  resetPassword: 'ResetPassword',
  OTP: 'OTP',
  map: 'Map',
  route: 'Route',
  account: 'Account',
  scanner: 'Scanner',
  scanOrderNoReceived: 'ScanOrderNoReceived',
  scanDeliveryReceived: 'ScanDeliveryReceived',
  scanOrderReceived: 'ScanOrderReceived',
  order: 'Order',
  orderNoReceived: 'OrderNoReceived',
  orderReceived: 'OrderReceived',
  searchDeliveryReceived: 'SearchDeliveryReceived',
  accountOrder: 'AccountOrder',
  history: 'History',
  accounthistory: 'AccountHistory',
  customerHistory: 'CustomerHistory',
  orderHistory: 'OrderHistory',
  orderHistoryFilter: 'OrderHistoryFilter',
  routeHistory: 'RouteHistory',
  routeDetail: 'RouteDetail',
  customerRouteDetail: 'CustomerRouteDetail',
  customerOrderDetail: 'CustomerOrderDetail',
  search: 'Search',
  changePassword: 'ChangePassword',
  customerMapDetail: 'CustomerMapDetail',
  userInfo: 'UserInfo',
  selectAddress: 'SelectAddress',
  notification: 'Notification',
  routeListHistory: 'RouteListHistory',
  accountRouteListHistory: 'AccountRouteListHistory',
  routeDetailHistory: 'RouteDetailHistory',
  customerRouteDetailHistory: 'CustomerRouteDetailHistory',
  customerOrderDetailHistory: 'CustomerOrderDetailHistory',
  orderSearchDetail: 'OrderSearchDetail',
  printer: 'Printer',
}

export const TABS = {
  home: 'HomeTab',
  history: 'HistoryTab',
  map: 'MapTab',
  account: 'AccountTab',
  order: 'OrderTab',
}

export const SCREEN_HIDE_TAB_BAR = [
  TABS.map,
  // TABS.order,
  NAVIGATION.map,
  NAVIGATION.scanner,
  NAVIGATION.customerHistory,
  NAVIGATION.orderHistory,
  NAVIGATION.routeHistory,
  NAVIGATION.routeDetail,
  NAVIGATION.customerRouteDetail,
  NAVIGATION.routeDetail,
  NAVIGATION.customerOrderDetail,
  NAVIGATION.search,
  NAVIGATION.phone,
  NAVIGATION.resetPassword,
  NAVIGATION.OTP,
  NAVIGATION.changePassword,
  NAVIGATION.customerMapDetail,
  NAVIGATION.orderHistoryFilter,
  NAVIGATION.userInfo,
  NAVIGATION.selectAddress,
  NAVIGATION.notification,
  NAVIGATION.routeDetailHistory,
  NAVIGATION.customerRouteDetailHistory,
  NAVIGATION.customerOrderDetailHistory,
  // NAVIGATION.order,
  NAVIGATION.accounthistory,
  NAVIGATION.accountOrder,
  NAVIGATION.accountRouteListHistory,
  NAVIGATION.scanOrderNoReceived,
  NAVIGATION.orderSearchDetail,
  NAVIGATION.orderNoReceived,
  NAVIGATION.orderReceived,
  NAVIGATION.scanOrderReceived,
  NAVIGATION.scanOrderNoReceived,
  NAVIGATION.scanDeliveryReceived,
  NAVIGATION.printer,
]
